### ISSUE TITLE
Crash on Gobbers w/crossbows loading and ready to fire

### ISSUE THREAD

**Issue by VallenFrostweaver** [superlord9362/GoblinsAndDungeons#15]
Minecraft 1.18.1
Forge 39.0.75
Goblins & Dungeons 1.0.5

Gobbers with crossbows can crash things. Once their animation gets to loading the crossbow the game crashes.
[https://hastebin.skyra.pw/ecegitirus.nestedtext](https://hastebin.skyra.pw/ecegitirus.nestedtext)

**Comment by superlord9362** [comment]
Fixed for 1.0.6

**Comment by VallenFrostweaver** [comment]
Updated to 1.0.6 - no change. Still crashes with same result.
Updated to Forge 39.1.2 - no change. Still crashes with same result.

I took a screen shot of the crash window that pops up from the launcher (GDLauncher) I am using as well in case it may help.
![image](https://user-images.githubusercontent.com/13642054/157053441-68d2dd62-ae89-4f7d-b37f-279dcd5e45e1.png)
